### ISSUE TITLE
working?

### ISSUE THREAD

**Issue by stevepowell99** [akhayyat/pelican-page-hierarchy#3]
Great idea - but why just for pages? Is there a way to tweak it to make it work for articles too? I store my articles in folders as categories.

**Comment by akhayyat** [comment]
You can use folders as categories without any plugins. Pelican already supports this setup. See the `USE_FOLDER_AS_CATEGORY`setting in the [Pelican Settings docs](http://docs.getpelican.com/en/latest/settings.html#basic-settings).

**Comment by stevepowell99** [comment]
Thanks. USE_FOLDER_AS_CATEGORY doesn't support parent and child links for templates though.
