### ISSUE TITLE
Page parent and children properties do not seem to be working

### ISSUE THREAD

**Issue by plaes** [akhayyat/pelican-page-hierarchy#4]
With Pelican 5.0 I'm currently trying to filter out sub-pages from the menu and I was hoping that I could do it like this:
```
{% for p in PAGES %}
  {% if p.parent is None %}
    {{ p }} {# Show link #}
  {% endif %}
{% endfor %}
```

But this doesn't seem to be working as `p.parent` is always `None`.

**Comment by akhayyat** [comment]
When I try your template snippet, pelican complains with:

    CRITICAL: no test named 'None'

Try replacing `{% if p.parent is None %}` with `{% if not p.parent %}`.

**Comment by akhayyat** [comment]
Does this fix your issue, @plaes ?

**Comment by plaes** [comment]
Yup, I mixed up Jinja syntax with Python.
